### ISSUE TITLE
Builder panic

### ISSUE THREAD

**Issue by EddyLane** [velocity-ci/velocity#54]
I'm not 100% sure of the circumstances that led to it, but I've had this the builder crash on me a couple of times now from normal use of the application.

The builder output is here:

```
builder_1    | 2018-07-22T15:22:05.290Z	INFO	builder/builder.go:125	got known hosts	{"payload": {"knownHosts":[{"id":"8ce0d182-8b8c-11e8-94cb-0242ac130002","entry":"# github.com:22 SSH-2.0-libssh_0.7.0\ngithub.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\n# github.com:22 SSH-2.0-libssh_0.7.0\n# github.com:22 SSH-2.0-libssh_0.7.0","hosts":["github.com"],"comment":"","sha256":"SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8","md5":"16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"}]}}
builder_1    | 2018-07-22T15:22:05.300Z	DEBUG	knownhost/file.go:52	added entry to known-hosts file	{"entry": "# github.com:22 SSH-2.0-libssh_0.7.0\ngithub.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\n# github.com:22 SSH-2.0-libssh_0.7.0\n# github.com:22 SSH-2.0-libssh_0.7.0", "path": "/root/.ssh/known_hosts"}
builder_1    | 2018-07-22T15:22:05.310Z	INFO	builder/builder.go:122	got build	{"payload": {"build":{"id":"946c6baf-0e37-32a5-8ebd-175f0c750432","task":{"id":"1bf21f42-81c1-30d8-9512-2283fccec72c","commit":{"id":"ceb76870-a788-3462-bb65-774cb8f89e77","project":{"id":"8d5d8e0d-8b8c-11e8-94cb-0242ac130002","slug":"velocity","name":"Velocity","repoConfig":{"address":"https://github.com/velocity-ci/velocity.git","privateKey":""},"createdAt":"2018-07-19T19:47:21.0232421Z","updatedAt":"2018-07-21T00:10:46.154948Z","synchronising":false,"project":{"name":"","logo":"","tasksPath":""},"git":{"depth":0},"paramaters":null,"plugins":null,"stages":null},"hash":"b14e92dd988fb2b0273f0bc9a9a6e8e91015683d","author":"vj@vjpatel.me","createdAt":"2018-07-19T18:36:45Z","message":"Not saving carriage returns to DB so ensuring that every line has a new-line","signed":""},"slug":"compose-example-streams","vTask":{"name":"compose-example-streams","description":"Example using docker-compose files to output multiple streams at once","git":{"submodule":false},"docker":{"registries":[]},"parameters":[],"steps":[{"type":"setup","description":"","outputStreams":["setup"],"params":null},{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}}]}},"parameters":{},"status":"running","createdAt":"2018-07-22T15:22:04.488561Z","updatedAt":"2018-07-22T15:22:04.488561Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"steps":[{"id":"16856742-73b2-3d3e-9816-246079df87f8","build":null,"number":0,"step":{"type":"setup","description":"","outputStreams":["setup"],"params":null},"status":"waiting","updatedAt":"2018-07-22T15:22:04.4955444Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},{"id":"0348b3e0-fa18-399f-ad4e-b84feecd747e","build":null,"number":1,"step":{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}},"status":"waiting","updatedAt":"2018-07-22T15:22:04.5059063Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"}],"streams":[{"id":"a7204221-fdd5-3b47-9531-2b5662128755","step":{"id":"16856742-73b2-3d3e-9816-246079df87f8","build":null,"number":0,"step":{"type":"setup","description":"","outputStreams":["setup"],"params":null},"status":"waiting","updatedAt":"2018-07-22T15:22:04.4955444Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"name":"setup","status":""},{"id":"40b676f9-0998-30d8-9e59-dd84b38da4c9","step":{"id":"0348b3e0-fa18-399f-ad4e-b84feecd747e","build":null,"number":1,"step":{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}},"status":"waiting","updatedAt":"2018-07-22T15:22:04.5059063Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"name":"b","status":""},{"id":"5bb9d60d-9281-376a-96ec-1480188bc431","step":{"id":"0348b3e0-fa18-399f-ad4e-b84feecd747e","build":null,"number":1,"step":{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}},"status":"waiting","updatedAt":"2018-07-22T15:22:04.5059063Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"name":"a","status":""},{"id":"91544a2b-40c1-3faa-b863-c438a1b353b8","step":{"id":"0348b3e0-fa18-399f-ad4e-b84feecd747e","build":null,"number":1,"step":{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}},"status":"waiting","updatedAt":"2018-07-22T15:22:04.5059063Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"name":"c","status":""},{"id":"cbe55793-1586-3daf-be9f-6ef7104bd9c9","step":{"id":"0348b3e0-fa18-399f-ad4e-b84feecd747e","build":null,"number":1,"step":{"type":"compose","description":"","outputStreams":["c","d","a","b"],"params":{},"composeFile":"tasks/example.compose.2.yml","Contents":{"services":{"a":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","b"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["a"]}}},"b":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","c"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["b"]}}},"c":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","d"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["c"]}}},"d":{"image":"busybox","build":{"context":"","dockerfile":""},"workingDir":"","command":["ping","-c","20","a"],"links":null,"environment":{},"volumes":null,"expose":null,"networks":{"default":{"aliases":["d"]}}}}}},"status":"waiting","updatedAt":"2018-07-22T15:22:04.5059063Z","startedAt":"0001-01-01T00:00:00Z","completedAt":"0001-01-01T00:00:00Z"},"name":"d","status":""}]}}
builder_1    | 2018-07-22T15:22:05.424Z	INFO	velocity/git.go:169	cloning repository	{"cmd": "git fetch --progress --depth=1 --recurse-submodules"}
builder_1    | 2018-07-22T15:22:09.263Z	INFO	velocity/git.go:199	cloned repository	{"address": "https://github.com/velocity-ci/velocity.git"}
builder_1    | 2018-07-22T15:22:09.343Z	ERROR	velocity/git.go:329	non-zero exit in git	{"stdout": [], "stderr": ["fatal: reference is not a tree: b14e92dd988fb2b0273f0bc9a9a6e8e91015683d"]}
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.handleStatusError
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/git.go:329
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.(*RawRepository).Checkout
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/git.go:347
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.(*Setup).Execute
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/setup.go:82
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.runBuild
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/build.go:33
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.monitorCommands
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/builder.go:123
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.(*Builder).Start
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/builder.go:39
builder_1    | 2018-07-22T15:22:09.349Z	DEBUG	velocity/git.go:351	checked out	{"reference": "b14e92dd988fb2b0273f0bc9a9a6e8e91015683d", "repository": "/opt/velocityci/workspaces/_https-github-com-velocity-ci-velocity-git-7712527605672772416"}
builder_1    | panic: runtime error: index out of range
builder_1    |
builder_1    | goroutine 6 [running]:
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.(*RawRepository).GetCommitInfo(0xc42006c440, 0xc42014b5e8, 0x4, 0x0)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/git.go:279 +0x589
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.(*RawRepository).GetCurrentCommitInfo(0xc42006c440, 0x0)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/git.go:298 +0x1ad
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.getGitParams(0xc42041a150)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/setup.go:163 +0x89
builder_1    | github.com/velocity-ci/velocity/backend/pkg/velocity.(*Setup).Execute(0xc4203cc200, 0xa67ee0, 0xc4204162d0, 0xc4202d2630, 0x6, 0x9)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/velocity/setup.go:98 +0x209
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.runBuild(0xc4204043c0, 0xc420480000)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/build.go:33 +0x2ae
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.monitorCommands(0xc420480000)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/builder.go:123 +0x362
builder_1    | github.com/velocity-ci/velocity/backend/pkg/builder.(*Builder).Start(0xc420357380)
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/pkg/builder/builder.go:39 +0xd9
builder_1    | created by main.main
builder_1    | 	/go/src/github.com/velocity-ci/velocity/backend/cmd/vci-builder/main.go:15 +0x69
builder_1    | exit status 2
```

**Comment by EddyLane** [comment]
This particular instance was just attempting a build, after using the same application (and task) successfully for a fair amount of time.

let me know if I can do anymore to narrow down the cause

**Comment by EddyLane** [comment]
I can actually get this reliably whenever I restart the builder @VJftw so give me a shout if I can help you debug this one :)

**Comment by VJftw** [comment]
I have seen this before, but can't seem to get it again at the moment. I'll add in much better handling of errors during builds though and we shouldn't really see any panics so i'll program that a bit more defensively
