### ISSUE TITLE
Can't build web

### ISSUE THREAD

**Issue by VJftw** [velocity-ci/velocity#58]
```─ make build 
Building frontend release

[at-loader] Using typescript@2.5.3 from typescript and "tsconfig.json" from /app/tsconfig.json.

WARNING: The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
Backtrace:
	node_modules/bootstrap/scss/mixins/_text-hide.scss:10, in mixin `text-hide`
	node_modules/bootstrap/scss/utilities/_text.scss:57


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.234 sec.
Hash: 072d3fb9ac4af9f63071
Version: webpack 3.6.0
Time: 3240ms
                                        Asset       Size  Chunks                    Chunk Names
         static/fonts/fontawesome-webfont.eot     166 kB          [emitted]         
         static/fonts/fontawesome-webfont.svg     444 kB          [emitted]  [big]  
         static/fonts/fontawesome-webfont.ttf     166 kB          [emitted]         
       static/fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]         
        static/fonts/fontawesome-webfont.woff      98 kB          [emitted]         
static/js/main.072d3fb9ac4af9f63071.bundle.js     233 kB       0  [emitted]         main
     static/css/main.fa51cd7e7baa29950ef3.css     200 kB       0  [emitted]         main
                                   index.html  475 bytes          [emitted]         
[./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/style-loader/index.js!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/styles.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/style-loader!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/styles.scss 163 bytes {0} [built]
[./src/app/Main.elm] ./src/app/Main.elm 778 bytes {0} [built] [failed] [1 error]
[./src/main.ts] ./src/main.ts 1.4 kB {0} [built]
[./src/styles.scss] ./src/styles.scss 1.69 kB {0} [built]
    + 11 hidden modules

ERROR in ./src/app/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
I found multiple modules named 'Bootstrap.Dropdown'.

Module 'Main' is trying to import it.

Modules with that name were found in the following locations:

    directory ././elm-bootstrap/src/Bootstrap/Dropdown.elm
    package rundis/elm-bootstrap


    at ChildProcess.<anonymous> (/app/node_modules/node-elm-compiler/index.js:141:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
 @ ./src/main.ts 9:10-35
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 682 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/styles.scss:
                                     Asset     Size  Chunks                    Chunk Names
      static/fonts/fontawesome-webfont.eot   166 kB          [emitted]         
      static/fonts/fontawesome-webfont.svg   444 kB          [emitted]  [big]  
      static/fonts/fontawesome-webfont.ttf   166 kB          [emitted]         
    static/fonts/fontawesome-webfont.woff2  77.2 kB          [emitted]         
     static/fonts/fontawesome-webfont.woff    98 kB          [emitted]         
    [./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/styles.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/styles.scss 212 kB {0} [built]
        + 7 hidden modules
make: *** [Makefile:18: build] Error 2
```

**Comment by VJftw** [comment]
Getting the same in `make serve` too :(

**Comment by VJftw** [comment]
just needed to remove old `elm-bootstrap`
